from pydantic import BaseModel

class Claim(BaseModel):
    Type: int
    Coverage: int
    Coverage_Add_Ons: int
    Policy_Status: int
    Insured_amount: int
    Premium_amount: float
    Payment_status: int
    Payment_Frequency: int
    Claimant_age: int
    Vehicle_condition: int
    Vehicle_value_market_value: float
    Vehicle_type_sedan_SUV_etc: int
    Fuel_type: int
    Insurance_coverage_type: int
    Odometer_reading: int
    Nature_of_incident: int
    Weather_conditions_at_the_time_of_the_accident: int
    Cause_of_incident: int
    Own_Damage: bool
    Third_Party: bool
    Comprehensive: bool
    Extent_of_damage: int
    Repair_estimates: float
    Repair_Cost: float
    Depreciation: float
    Salvage_value: float
    Insurance_settlement_amount: float
    Repair_duration: int
    Deductibles: float
    Previous_claims: int
    Claim_status: int
    Disability_status: bool
    Loss_of_wages: int
    Red_flags: bool
    Court_cases: bool
    Final_settlement_approval: bool
    Claim_verification: int
    Fraud_detection_approval: int
    Driver_history: int
    Driving_experience: int
    Previous_traffic_violations: int
    Alcohol_drug_test_results: int
    License_class_if_applicable: int
    License_Type: int
    Validity_days: int
    License_expire_days: int
    Policy_renewal_days: int
